name: 'AWS SSM Send-Command'
author: 'Donghyun Peter Kim <peterkimzz69@gmail.com>'

branding:
  icon: 'arrow-up-right'
  color: 'orange'

description: 'Remote EC2 bash command execution.'

inputs:
  instance_id:
    required: true
    description: 'AWS EC2 Instance id'
  commands:
    required: true
    description: 'Bash command you want to execute'
  document_name:
    description: 'Script Environment'
    default: 'AWS-RunShellScript'
  working_directory:
    require: false
    description: 'Command execution location'
    default: ''
  comment:
    require: false
    description: 'Comment for Send-Command'
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
